name: animal_health_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Theming
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^8.0.0
  google_fonts: ^6.3.1
  fl_chart: ^1.0.0

  # State Management
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  
  # Routing
  go_router: ^16.0.0

  # Dependency Injection
  get_it: ^8.0.0
  injectable: ^2.4.1

  # HTTP Client
  dio: ^5.4.3+1
  
  # Utilities
  intl: ^0.20.0
  equatable: ^2.0.5
  provider: ^6.1.5+1
  animations: ^2.0.11
  meta: ^1.16.0

  # Data
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  vector_math: ^2.2.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  build_runner: ^2.7.1
  injectable_generator: ^2.6.1
  freezed: ^3.2.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
